#!/bin/sh
set -e
# Automatically added by dh_systemd_start
if [ -d /run/systemd/system ]; then
	deb-systemd-invoke stop iptables-rules.service >/dev/null
fi
# End automatically added section
# Automatically added by dh_installinit
if [ -x "/etc/init.d/iptables-rules" ] || [ -e "/etc/init/iptables-rules.conf" ]; then
	invoke-rc.d iptables-rules stop || exit $?
fi
# End automatically added section
